version: 2
registries:
  docker-registry-docker-all-artifactory-fiks-ks-no:
    type: docker-registry
    url: https://docker-all.artifactory.fiks.ks.no
    username: tok-dependabot
    password: "${{secrets.DOCKER_REGISTRY_DOCKER_ALL_ARTIFACTORY_FIKS_KS_NO_PASSWORD}}"
updates:
- package-ecosystem: docker
  directory: "/nginx"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15
  registries:
  - docker-registry-docker-all-artifactory-fiks-ks-no
